import { normalizeTitle } from "@/lib/utils";
import type { Showtime } from "./types";

export type SeatHit = { rest: number; total: number | null; at?: number; source?: string };
export type SeatHitMap = Record<string, SeatHit>;

const SITE_NO: Record<string, string> = { cgv_yongsan: "0013", cgv_yeongdeungpo: "0059", megabox_coex: "1351", megabox_namyangju: "0019" };
export function applyCgvSeatHits(rows: Showtime[], map: SeatHitMap, overwrite = false, asLive = true): Showtime[] { const stampKeep = (row: Showtime): Showtime => { if (typeof row.restSeats !== "number" || !Number.isFinite(row.restSeats)) return { ...row, seatLive: false }; return { ...row, seatLive: row.seatLive ?? true }; }; if (!Object.keys(map).length) return rows.map(stampKeep); return rows.map((row) => { const had = typeof row.restSeats === "number" && Number.isFinite(row.restSeats); const hit = lookupSeatHit(row, map); if (!hit) return stampKeep(row); const hitAt = typeof hit.at === "number" && Number.isFinite(hit.at) ? hit.at : null; const currentAt = row.seatCheckedAt ? new Date(row.seatCheckedAt).getTime() : 0; if (hitAt != null && had && !overwrite && currentAt >= hitAt) return row; if (hitAt != null && had && overwrite && currentAt > 0 && hitAt < currentAt) return row; return { ...row, restSeats: hit.rest, totalSeats: hit.total ?? row.totalSeats, seatLive: asLive, seatCheckedAt: hitAt != null ? new Date(hitAt).toISOString() : (row.seatCheckedAt ?? null), seatSource: hit.source ?? row.seatSource }; }); }
export function indexSeatHit(map: SeatHitMap, row: { theaterId: string; playDate: string; startTime: string; movieTitle?: string; hallName?: string; movieNo?: string; chain?: "cgv" | "megabox" }, rec: SeatHit) { const chain = row.chain ?? (String(row.theaterId).startsWith("cgv") ? "cgv" : "megabox"); for (const key of seatLookupKeys({ id: "", theaterId: row.theaterId as Showtime["theaterId"], theaterName: "", chain, movieTitle: row.movieTitle || "", movieNo: row.movieNo || "", playDate: row.playDate, startTime: row.startTime, endTime: null, hallName: row.hallName || "", formats: [], restSeats: rec.rest, totalSeats: rec.total, bookingUrl: "", bookable: true })) map[key] = { ...rec, at: rec.at }; }
export function putSeatHit(map: SeatHitMap, row: Showtime) { if (typeof row.restSeats !== "number" || !Number.isFinite(row.restSeats)) return; if (row.seatLive === false) return; const at = row.seatCheckedAt ? new Date(row.seatCheckedAt).getTime() : undefined; indexSeatHit(map, row, { rest: row.restSeats, total: row.totalSeats, at: at != null && Number.isFinite(at) ? at : undefined, source: row.seatSource }); }
function packHit(hit: SeatHit): SeatHit { return { rest: hit.rest, total: hit.total ?? null, at: hit.at, source: hit.source }; }
export function lookupSeatHit(row: Showtime, map: SeatHitMap): SeatHit | null { const hits: SeatHit[] = []; for (const key of seatLookupKeys(row)) { const hit = map[key]; if (hit && typeof hit.rest === "number" && Number.isFinite(hit.rest)) hits.push(hit); } const siteNo = SITE_NO[row.theaterId] ?? ""; if (siteNo) { const tag = row.chain === "cgv" ? "k" : "m"; for (const clock of clockVariants(row.playDate, row.startTime)) { const prefix = `${tag}:${siteNo}|${clock.playDate}|${clock.startTime}|`; const halls = hallVariants(row.hallName); if (halls.length) { for (const hall of halls) { const hit = map[`${prefix}${hall}`]; if (hit && typeof hit.rest === "number" && Number.isFinite(hit.rest)) hits.push(hit); } } else { for (const fallback of [normalizeTitle(row.movieTitle), row.movieNo].filter(Boolean)) { const hit = map[`${prefix}${fallback}`]; if (hit && typeof hit.rest === "number" && Number.isFinite(hit.rest)) hits.push(hit); } } } } if (!hits.length) return null; return packHit(hits.reduce((best, hit) => (hit.at ?? 0) >= (best.at ?? 0) ? hit : best)); }
export function seatLookupKeys(row: Showtime): string[] { const titleKey = normalizeTitle(row.movieTitle); const siteNo = SITE_NO[row.theaterId] ?? ""; const prefix = row.chain === "cgv" ? "k:" : "m:"; const keys = [row.id]; const rowHalls = hallVariants(row.hallName); for (const clock of clockVariants(row.playDate, row.startTime)) { const stem = siteNo ? `${prefix}${siteNo}|${clock.playDate}|${clock.startTime}` : ""; if (!stem) continue; for (const hall of rowHalls) keys.push(`${stem}|${hall}`); if (!rowHalls.length) { if (titleKey) keys.push(`${stem}|${titleKey}`); if (row.movieNo) keys.push(`${stem}|${row.movieNo}`); } } return [...new Set(keys.filter(Boolean))]; }
export function hallVariants(hall: string): string[] { const base = normHall(hall); const stripped = base.replace(/\[.*?\]/g, ""); const loose = stripped.replace(/관$/, ""); const titled = normalizeTitle(hall); return [...new Set([base, stripped, loose, `${loose}관`, titled].filter(Boolean))]; }
export function clockVariants(playDate: string, startTime: string): { playDate: string; startTime: string }[] { const time = parseClock(startTime); if (!time) return []; const out = [{ playDate, startTime: time.hhmm }]; if (time.hour >= 24 && playDate.length === 8) { out.push({ playDate: addYmd(playDate, 1), startTime: `${String(time.hour - 24).padStart(2, "0")}:${time.minute}` }); out.push({ playDate, startTime: `${time.hour}:${time.minute}` }); } if (time.hour < 4 && playDate.length === 8) out.push({ playDate: addYmd(playDate, -1), startTime: `${time.hour + 24}:${time.minute}` }); return out; }
export function parseClock(raw: string): { hour: number; minute: string; hhmm: string } | null { const digits = String(raw || "").replace(/\D/g, ""); if (digits.length < 3) return null; const padded = digits.length === 3 ? `0${digits}` : digits.slice(0, 4); const hour = Number(padded.slice(0, padded.length - 2)); const minute = padded.slice(-2); if (!Number.isFinite(hour) || Number(minute) > 59) return null; const hhmm = `${String(hour % 24).padStart(2, "0")}:${minute}`; return { hour, minute, hhmm: hour >= 24 ? `${hour}:${minute}` : hhmm }; }
function addYmd(ymd: string, days: number) { const y = Number(ymd.slice(0, 4)); const m = Number(ymd.slice(4, 6)); const d = Number(ymd.slice(6, 8)); const dt = new Date(Date.UTC(y, m - 1, d + days)); return `${dt.getUTCFullYear()}${String(dt.getUTCMonth() + 1).padStart(2, "0")}${String(dt.getUTCDate()).padStart(2, "0")}`; }
export function normTime(time: string) { const parsed = parseClock(time); return parsed?.hhmm ?? String(time || "").trim(); }
function normHall(hall: string) { return String(hall || "").toUpperCase().replace(/[\s|]+/g, ""); }
export function hallsMatch(a: string, b: string) { const aa = hallVariants(a); const bb = hallVariants(b); if (!aa.length || !bb.length) return false; return aa.some((v) => bb.includes(v)); }
