/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoRouteImport } from './routes/go'
import { Route as KakaoRouteImport } from './routes/kakao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiGasBindRouteImport } from './routes/api/gas-bind'
import { Route as ApiWatchTickRouteImport } from './routes/api/watch-tick'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const KakaoRoute = KakaoRouteImport.update({
  id: '/kakao',
  path: '/kakao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGasBindRoute = ApiGasBindRouteImport.update({
  id: '/api/gas-bind',
  path: '/api/gas-bind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchTickRoute = ApiWatchTickRouteImport.update({
  id: '/api/watch-tick',
  path: '/api/watch-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/kakao': typeof KakaoRoute
  '/login': typeof LoginRoute
  '/api/gas-bind': typeof ApiGasBindRoute
  '/api/watch-tick': typeof ApiWatchTickRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/kakao': typeof KakaoRoute
  '/login': typeof LoginRoute
  '/api/gas-bind': typeof ApiGasBindRoute
  '/api/watch-tick': typeof ApiWatchTickRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/kakao': typeof KakaoRoute
  '/login': typeof LoginRoute
  '/api/gas-bind': typeof ApiGasBindRoute
  '/api/watch-tick': typeof ApiWatchTickRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/go'
    | '/kakao'
    | '/login'
    | '/api/gas-bind'
    | '/api/watch-tick'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/go'
    | '/kakao'
    | '/login'
    | '/api/gas-bind'
    | '/api/watch-tick'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/go'
    | '/kakao'
    | '/login'
    | '/api/gas-bind'
    | '/api/watch-tick'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoRoute: typeof GoRoute
  KakaoRoute: typeof KakaoRoute
  LoginRoute: typeof LoginRoute
  ApiGasBindRoute: typeof ApiGasBindRoute
  ApiWatchTickRoute: typeof ApiWatchTickRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kakao': {
      id: '/kakao'
      path: '/kakao'
      fullPath: '/kakao'
      preLoaderRoute: typeof KakaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gas-bind': {
      id: '/api/gas-bind'
      path: '/api/gas-bind'
      fullPath: '/api/gas-bind'
      preLoaderRoute: typeof ApiGasBindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-tick': {
      id: '/api/watch-tick'
      path: '/api/watch-tick'
      fullPath: '/api/watch-tick'
      preLoaderRoute: typeof ApiWatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoRoute: GoRoute,
  KakaoRoute: KakaoRoute,
  LoginRoute: LoginRoute,
  ApiGasBindRoute: ApiGasBindRoute,
  ApiWatchTickRoute: ApiWatchTickRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
